### ISSUE TITLE
url from ready

### ISSUE THREAD

**Issue by Saiyan1** [martinbean/api-framework#5]
Hi,
Ive downloaded your project.
I put on my web server but with the dummy url you are providing, it is not working.

Im trying with : http://localhost/bmapi/api/news/

Is it ok?

Thanks!!!

**Comment by fatdreads** [comment]
Hi, 
this api isn´t written by me, so i can´t give an support!
if you wanna use a php rest api you might use http://www.slimframework.com/ ;)
i´ve done a little tutorial, but it´s in german... 
so read the code and use google translator or something like that.
http://www.3dan.de/tutorial-unity3d-slim-framework-1/
http://www.3dan.de/tutorial-unity3d-slim-framework-2/
http://www.3dan.de/tutorial-unity3d-slim-framework-3/
http://www.3dan.de/tutorial-unity3d-slim-framework-4/

cheers!

**Comment by Saiyan1** [comment]
Thanks!

Cheers from Argentina

**Comment by fatdreads** [comment]
you´re welcome, man! :)
hope it helps

greetings from germany!

**Comment by martinbean** [comment]
@fatdreads Please don’t hijack other repo’s issues.

**Comment by martinbean** [comment]
@Saiyan1 Can you elaborate on how it’s “not working”? How _specifically_ is it not working? Do you get an error message?

**Comment by Saiyan1** [comment]
Ive tried to access the API via the url you provide as an example and it
does not work.
Also, on NewsController ive noticed that theres an undefined variable
($articles)

Am I wrong?

Cheers!

---
Gustavo Insaurralde

2015-07-03 13:05 GMT-03:00 Martin Bean <notifications@github.com>:

**Comment by martinbean** [comment]
@Saiyan1 I’m not sure what you mean by the URL I provide as an example. Which URL?

This package will need _some_ configuring to run on your website server at a domain of your choosing.

**Comment by Saiyan1** [comment]
*http://example.com/api/[resource]/[id]
<http://example.com/api/%5Bresource%5D/%5Bid%5D>*.

I try with "localhost/api/news" and I cant get any response


---
Gustavo Insaurralde

2015-07-03 16:51 GMT-03:00 Martin Bean <notifications@github.com>:

**Comment by martinbean** [comment]
@Saiyan1 Sorry, but this is a web server issue and I don’t know how you’ve configured your web server, so unable to help.

**Comment by Saiyan1** [comment]
Ok, thanks!

have you specified anywhere this configs youre telling me?

---
Gustavo Insaurralde

2015-07-03 17:30 GMT-03:00 Martin Bean <notifications@github.com>:
